### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by VShawn** [15010159959/super-dictionary#5]
流程 --->输入信息，点击搜索 --->搜索成功 ，显示搜索结果 --->**索索失败** --->显示 是否需要添加相应的信息 --->点击添加，出现输入信息框-->提交

那个“索索失败”是搜索失败的错别字吧？

**Comment by ChengOrangeJu** [comment]
sure :) Thanks!

**Comment by yupnano** [comment]
Readme已更新，现在介绍的更详细了。
